# Generated by Django 2.0.4 on 2018-04-26 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_auto_20180425_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Revenue'),
        ),
    ]
