# Generated by Django 2.0.4 on 2018-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='correct_order',
            field=models.BooleanField(default=True, verbose_name='Correct order'),
        ),
    ]
