# Generated by Django 2.0.4 on 2018-05-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180510_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcompany',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Raw company name'),
        ),
    ]
