# Generated by Django 2.0.4 on 2018-05-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20180510_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawcompany',
            name='cleaned_name',
        ),
        migrations.AddField(
            model_name='company',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
    ]
